### ISSUE TITLE
`(1 - 1) != 0` in the emulator (because `0 != 0.0`)

### ISSUE THREAD

**Issue by MinekPo1** [Its-Jakey/SCPP#10]
The following code looks like it should output `1 - 1 == 0`:

```SCPP
namespace test {
	public func main() {
		if ((1 - 1) == 0) {
			print("1 - 1 == 0");
			return;
		}
		print("1 - 1 != 0");
	}
}
```

And it does when run in the SLVM:

![image](https://user-images.githubusercontent.com/68391527/180518526-daaa5f29-9a82-4a5c-9eda-c4b991d062d6.png)

But when run in the emulator:

![image](https://user-images.githubusercontent.com/68391527/180518736-5dea3620-064c-41ba-bdcf-b83b0f910464.png)

The reason for this is quite simple: According to the vm `0 != 0.0`

If we update the condition to be `(1 - 1) == 0.0` then it works.

![image](https://user-images.githubusercontent.com/68391527/180518990-dc9103dc-142f-42f2-ac5d-9e959784bfab.png)

**Comment by MinekPo1** [comment]
Also, small unrelated fact: the compiler gets to aggressive with equal operation leading to `2 - 1 == 0` evaluating to `2 - (1 == 0)` or `2.0`. yay :D

**Comment by MinekPo1** [comment]
(I know you said there are random errors, I'm just showing you them :) )

**Comment by Its-Jakey** [comment]
Thank you, I will get to work on this
